"""PyInstaller build script producing a portable single-file Windows exe.

Usage:
    python build.py            # full build
    python build.py --clean    # wipe build artefacts first
    python build.py --onedir   # folder build instead of onefile
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "GitHubManager"
ENTRY = ROOT / "main.py"
DIST = ROOT / "dist"
BUILD = ROOT / "build"
SPEC = ROOT / f"{APP_NAME}.spec"

HIDDEN_IMPORTS = [
    "PySide6.QtSvg",
    "PySide6.QtNetwork",
    "markdown_it",
    "markdown_it.rules_core.linkify",
    "pygments",
    "pygments.lexers",
    "pygments.formatters",
    "requests",
    "urllib3",
    "certifi",
    "github",
    "github.Auth",
    "cryptography",
    "nacl",
]

EXCLUDES = [
    "tkinter",
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "PySide6.QtQml",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtMultimedia",
    "PySide6.Qt3DCore",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtBluetooth",
    "PySide6.QtPositioning",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
]


def run(args: list[str]) -> None:
    print(f"\n$ {' '.join(args)}\n")
    result = subprocess.run(args, cwd=str(ROOT))
    if result.returncode != 0:
        raise SystemExit(f"Command failed with code {result.returncode}")


def make_icon() -> Path | None:
    """Render an .ico at build time so no binary asset is checked in."""
    target = ROOT / "build_assets" / "icon.ico"
    if target.exists():
        return target
    try:
        os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
        from PySide6.QtCore import QSize, Qt
        from PySide6.QtGui import QColor, QIcon, QLinearGradient, QPainter, QPixmap
        from PySide6.QtWidgets import QApplication

        sys.path.insert(0, str(ROOT))
        from app.ui.widgets import icon_svg

        app = QApplication.instance() or QApplication([])

        icon = QIcon()
        for size in (16, 24, 32, 48, 64, 128, 256):
            pixmap = QPixmap(size, size)
            pixmap.fill(Qt.GlobalColor.transparent)
            painter = QPainter(pixmap)
            painter.setRenderHint(QPainter.RenderHint.Antialiasing)
            gradient = QLinearGradient(0, 0, size, size)
            gradient.setColorAt(0.0, QColor("#8b7cff"))
            gradient.setColorAt(1.0, QColor("#5b4bdb"))
            painter.setPen(Qt.PenStyle.NoPen)
            painter.setBrush(gradient)
            radius = size * 0.22
            painter.drawRoundedRect(0, 0, size, size, radius, radius)
            glyph_size = int(size * 0.62)
            glyph = icon_svg("git-branch", "#ffffff", glyph_size).pixmap(glyph_size, glyph_size)
            painter.drawPixmap((size - glyph_size) // 2, (size - glyph_size) // 2, glyph)
            painter.end()
            icon.addPixmap(pixmap)

        target.parent.mkdir(parents=True, exist_ok=True)
        # QIcon cannot write .ico, so save the largest pixmap through QImage.
        from PySide6.QtGui import QImage

        image = icon.pixmap(QSize(256, 256)).toImage()
        image.save(str(target), "ICO")
        print(f"icon written: {target}")
        return target if target.exists() else None
    except Exception as exc:  # pragma: no cover
        print(f"icon generation skipped: {exc}")
        return None


def version_info(icon: Path | None) -> Path | None:
    """Generate a Windows version resource so the exe has proper metadata."""
    target = ROOT / "build_assets" / "version_info.txt"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(1, 0, 0, 0),
    prodvers=(1, 0, 0, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'GitHub Manager'),
         StringStruct(u'FileDescription', u'GitHub Manager - AI powered GitHub client'),
         StringStruct(u'FileVersion', u'1.0.0'),
         StringStruct(u'InternalName', u'{APP_NAME}'),
         StringStruct(u'LegalCopyright', u'MIT'),
         StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
         StringStruct(u'ProductName', u'GitHub Manager'),
         StringStruct(u'ProductVersion', u'1.0.0')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
""",
        encoding="utf-8",
    )
    return target


SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py - do not edit by hand.

block_cipher = None

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports={hiddenimports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={excludes!r},
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,{icon_line}
)
'''


ONEDIR_TAIL = '''

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    name={name!r},
)
'''


def spec_text(icon: Path | None, onedir: bool) -> str:
    """Render the spec for a onefile (default) or onedir PyInstaller build.

    The flag is named ``onedir`` to match ``--onedir`` and its caller; getting
    this backwards silently produces a folder build while the script still
    reports a single portable file.
    """
    icon_line = f"\n    icon={str(icon)!r}," if icon else ""
    text = SPEC_TEMPLATE.format(
        hiddenimports=HIDDEN_IMPORTS,
        excludes=EXCLUDES,
        name=APP_NAME,
        icon_line=icon_line,
    )
    if not onedir:
        return text
    return text.replace(
        "exe = EXE(\n    pyz,\n    a.scripts,\n    a.binaries,\n    a.datas,\n    [],",
        "exe = EXE(\n    pyz,\n    a.scripts,\n    [],",
    ) + ONEDIR_TAIL.format(name=APP_NAME)


def main() -> int:
    args = sys.argv[1:]
    clean = "--clean" in args
    onedir = "--onedir" in args

    if clean:
        for path in (DIST, BUILD):
            if path.exists():
                print(f"removing {path}")
                shutil.rmtree(path, ignore_errors=True)
        if SPEC.exists():
            SPEC.unlink()

    run([sys.executable, "-m", "pip", "install", "--upgrade", "pyinstaller"])

    icon = make_icon()
    version_info(icon)

    SPEC.write_text(spec_text(icon, onedir), encoding="utf-8")
    print(f"spec written: {SPEC}")

    run([sys.executable, "-m", "PyInstaller", str(SPEC), "--noconfirm", "--clean"])

    target = DIST / (f"{APP_NAME}.exe" if not onedir else f"{APP_NAME}/{APP_NAME}.exe")
    if not target.exists():
        print("\nBuild finished but the executable was not found; check dist/.")
        return 1

    size_mb = target.stat().st_size / (1024 * 1024)
    print(f"\nBuild complete: {target}  ({size_mb:.1f} MB)")

    if not onedir:
        # A onefile build must be genuinely self-contained. If a folder build
        # slipped through, the exe silently depends on _internal\ next to it and
        # fails at launch with "Failed to load Python DLL", so catch it here.
        folder = DIST / APP_NAME
        if folder.exists():
            print(
                f"\nERROR: {folder} exists - this is a folder build, not a single "
                "file. The exe would not be portable."
            )
            return 1
        if size_mb < 20:
            print(
                f"\nERROR: the exe is only {size_mb:.1f} MB, which is too small to "
                "contain Qt. It will not start."
            )
            return 1

    print("Copy this single file anywhere - it is fully portable.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
